=== afmoller/javapeg/trunk/src/moller/javapeg/resources/thumbnailoverview/layout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://moller.javapeg.layout.com" xmlns:lay="http://moller.javapeg.layout.com" elementFormDefault="qualified">
    
    <xs:element name="document" type="lay:Document"/>
          
    <xs:complexType name="Document">
            <xs:sequence>
                <xs:element name="documenttitle" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="row" type="lay:Row" minOccurs="1" maxOccurs="1"/>    
            </xs:sequence>
        </xs:complexType>    
        
    <xs:complexType name="Row">
        <xs:sequence>
            <xs:element name="column" type="lay:Column" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="class"  type="xs:string"  use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="Column">
        <xs:sequence>
            <xs:element name="image" type="lay:Image" minOccurs="1" maxOccurs="1"/>
            <xs:element name="meta"  type="lay:Meta"  minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="class"  type="xs:string"  use="optional"/>
        <xs:attribute name="amount" type="xs:integer" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="Image">
        <xs:attribute name="class" type="xs:string" use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="Meta">
        <xs:sequence>
            <xs:element name="metaitem" type="lay:MetaItem" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="class"  type="xs:string"  use="optional"/>  
    </xs:complexType>
    
    <xs:complexType name="MetaItem">
        <xs:attribute name="class" type="xs:string" use="optional"/>
        <xs:attribute name="label" type="xs:string" use="required"/>
        <xs:attribute name="meta"  type="lay:MetaEnumeration" use="required"/>
    </xs:complexType>
        
    <xs:simpleType name="MetaEnumeration">
        <xs:restriction base="xs:string">
            <xs:enumeration value="fileName"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="time"/>
            <xs:enumeration value="cameraModel"/>
            <xs:enumeration value="exposureTime"/>
            <xs:enumeration value="isoValue"/>
            <xs:enumeration value="pictureWidth"/>
            <xs:enumeration value="pictureHeight"/>
            <xs:enumeration value="apertureValue"/>
            <xs:enumeration value="fileSize"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== afmoller/javapeg/javapeg-app/src/main/resources/thumbnailoverview/layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This section contains information about the syntax of the XML part of this file
 and which attributes that are valid for each tag. Below is a listing of all 
 valid tags and the use of them. See the layout.info file for the formal schema
 definition that this file must conform to.
  
 <documenttitle> 
 ===============
 Description: There can only be one instance of this tag and it shall be placed
              as a child to the <document> tag.
 
 Tag value  : The value of this tag will be put as title in the web browser. 
             
 Attributes : There are no attributes which are valid for this tag.
 
 
 <row>
 =====
 Description: There can only be one start and stop instance of this tag and it
              shall be placed as a child to the <document> tag.
 
 Tag value  : No value for this tag. 
 
 Attributes : The class attribute is optional and used by the CSS. This is the
              only valid attribute for this tag.
 
 
 <column>
 ========
 Description: There can only be one start and stop instance of this tag and it
              shall be placed as a child to the <row> tag.
 
 Tag value  : No value for this tag.
   
 Attributes : class and amount are the two attributes that are valid for this 
              tag. The class attribute is optional, and used by the CSS. The
              amount attribute is mandatory and shall contain an integer value
              larger than zero. This attribute defines how many columns of 
              images that will be generated in the thumb nail overview.  
            
            
 <image/>
 ========
 Description: There can only be one instance of this tag and it shall be placed 
              as a child to the <column> tag.
 
 Tag value  : No value for this tag.
   
 Attributes : The class attribute is optional and used by the CSS. This is the
              only valid attribute for this tag.


 <meta>
 ======
 Description: There can only be one start and stop instance of this tag and it
              shall be placed as a child to the <column> tag.
 
 Tag value  : No value for this tag.
 
 Attributes : The class attribute is optional and used by the CSS. This is the
              only valid attribute for this tag.


<metaitem/>
===========
 Description: There can be several instances of this tag and they shall all be 
              placed as children to the <meta> tag.
 
 Tag value  : No value for this tag.
   
 Attributes : class, label and meta are the attributes that are valid for this 
              tag. The class attribute is optional, and used by the CSS. The
              label attribute is mandatory and shall contain a string value that
              will be a label for the meta data value that will be defined by 
              the last attribute, meta.
             
              Available values for the meta attribute are:
             
              "fileName"
              "date"
              "time"
              "cameraModel"
              "exposureTime"
              "isoValue"
              "pictureWidth"
              "pictureHeight"
              "apertureValue"
              "fileSize"
  -->
<document xmlns="http://moller.javapeg.layout.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://moller.javapeg.layout.com layout.xsd">
  <documenttitle>Image overview</documenttitle>
  <row class="row">
    <column class="column" amount="5">
      <image class="image" />
      <meta class="meta">
        <metaitem class="metaitem" label="File size:" meta="fileSize" />
        <metaitem class="metaitem" label="Date:" meta="date" />
        <metaitem class="metaitem" label="Time:" meta="time" />
      </meta>
    </column>
  </row>
</document>
